### ISSUE TITLE
memJS  terminates connection to coherence

### ISSUE THREAD

**Issue by gvemula** [memcachier/memjs#124]
Hi,
Does anyone faced this issue? memJS abruptly issues this error and terminates our connection in proxy.

Logs from node
2019-07-15 16:43: MemJS GET: Internal error
2019-07-15 16:43: MemJS SET: Internal error
2019-07-15 16:43: MemJS SET: Internal error

logs from proxy
<Jul 7, 2019 1:29:34 PM CDT> <Error> <com.oracle.coherence> <BEA-000000> <2019-07-07 13:29:34.459/230955.455 Oracle Coherence GE 12.2.1.3.2 <Error> (thread=SelectionService(channels=57, selector=MultiplexedSelector(sun.nio.ch.EPollSelectorImpl@52fe8862), id=1183643794), member=n/a): Exception in handling memcached request: com.tangosol.net.ServiceStoppedException: Service lp:lp-bcc has been terminated
        at com.tangosol.coherence.component.util.daemon.queueProcessor.service.grid.partitionedService.PartitionedCache$ViewMap.onInvalidAccess(PartitionedCache.CDB:11)
        at com.tangosol.coherence.component.util.daemon.queueProcessor.service.grid.partitionedService.PartitionedCache$ViewMap.ensureBinaryMap(PartitionedCache.CDB:4)
        at com.tangosol.coherence.component.util.daemon.queueProcessor.service.grid.partitionedService.PartitionedCache$ViewMap.invoke(PartitionedCache.CDB:29)
        at com.tangosol.coherence.component.util.SafeNamedCache.invoke(SafeNamedCache.CDB:5)
        at com.tangosol.net.cache.NearCache.invoke(NearCache.java:466)
        at com.tangosol.coherence.memcached.DefaultRequestHandler.fireEP(DefaultRequestHandler.java:732)
        at com.tangosol.coherence.memcached.DefaultRequestHandler.onGet(DefaultRequestHandler.java:120)
        at com.tangosol.coherence.memcached.server.Task.handleRequest(Task.java:105)
        at com.tangosol.coherence.memcached.server.Task.run(Task.java:73)
        at com.tangosol.coherence.memcached.server.MemcachedServer$MessageHandler.onRequest(MemcachedServer.java:414)
        at com.tangosol.coherence.memcached.server.MemcachedServer$MessageHandler.handleRead(MemcachedServer.java:378)
        at com.tangosol.coherence.memcached.server.MemcachedServer$MessageHandler.onReadySafe(MemcachedServer.java:301)
        at com.oracle.common.net.SafeSelectionHandler.onReady(SafeSelectionHandler.java:88)
        at com.oracle.common.internal.net.RunnableSelectionService.process(RunnableSelectionService.java:401)
        at com.oracle.common.internal.net.RunnableSelectionService.run(RunnableSelectionService.java:274)

**Comment by saschat** [comment]
The `memjs` log output means that the client receives an "Internal error" from the server so there seems to be a problem with the Memcached server you are using.
